trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
- group: DTRACK_API 

jobs:
- job: Build_and_Upload_SBOM
  displayName: 'Générer et envoyer le SBOM pour .NET'
  steps:
  # L'étape de débogage n'est plus nécessaire, je l'ai enlevée pour plus de clarté.
  - task: UseDotNet@2
    displayName: 'Installer le SDK .NET 9.x' # MODIFIÉ
    inputs:
      packageType: 'sdk'
      version: '9.x' # MODIFIÉ
      includePreviewVersions: true # MODIFIÉ

  - task: DotNetCoreCLI@2
    displayName: 'Restaurer les dépendances NuGet'
    inputs:
      command: 'restore'
      # Vous avez mis le .sln à la racine, donc ce chemin est maintenant correct.
      projects: 'ResearchDependencyTrack.sln'

  - task: DotNetCoreCLI@2
    displayName: 'Installer l''outil CycloneDX pour .NET'
    inputs:
      command: 'custom'
      custom: 'tool'
      arguments: 'install --global CycloneDX.Tool'

  - script: |
      cyclonedx -i ResearchDependencyTrack.sln -o $(Build.ArtifactStagingDirectory)/sbom.json
    displayName: 'Générer le SBOM'

  - task: Bash@3
    displayName: 'Envoyer le SBOM à Dependency-Track'
    inputs:
      targetType: 'inline'
      script: |
        echo "Téléversement du fichier sbom.json vers Dependency-Track..."
        PROJECT_NAME="ResearchDependencyTrack"
        PROJECT_VERSION="$(Build.BuildNumber)"
        curl -X "POST" \
             -H "X-Api-Key: $(DTACK_API_KEY)" \
             -H "Content-Type: multipart/form-data" \
             -F "autoCreate=true" \
             -F "projectName=${PROJECT_NAME}" \
             -F "projectVersion=${PROJECT_VERSION}" \
             -F "bom=@$(Build.ArtifactStagingDirectory)/sbom.json" \
             "$(DT_API_URL)/api/v1/bom"
