trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  DTRACK_API_URL: 'https://dtrack-api.whitemeadow-13deb2f9.westeurope.azurecontainerapps.io'
  DTRACK_API_KEY: '$(DTRACK_API_KEY)' # à ajouter dans Azure DevOps > Library > Pipeline secrets

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: |
    dotnet tool install --global CycloneDX
  displayName: 'Install CycloneDX tool'

- script: |
    cd MonProjet
    dotnet cyclonedx --format json
  displayName: 'Generate SBOM with CycloneDX'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      curl -X PUT \
        "$(DTRACK_API_URL)/api/v1/bom" \
        -H "X-Api-Key: $(DTRACK_API_KEY)" \
        -H "Content-Type: application/json" \
        --data-binary "@MonProjet/bom.json"
  displayName: 'Upload SBOM to Dependency-Track'
